### ISSUE TITLE
Не логичный переход в "Пользователи"

### ISSUE THREAD

**Issue by mirkoles** [studio107/Admin#10]
В админке после обновления при переходе на пункт пользователи получаем вот это:
![screenshot 5](https://cloud.githubusercontent.com/assets/11004646/9130944/a4094ab8-3cef-11e5-8414-f11d5e9a1fcd.png)

**Comment by qantus** [comment]
Скорее всего ошибка в недостающих полях в БД. Включите дебаг и посмотрите ошибку.

**Comment by mirkoles** [comment]
```php
'code' => 500
            'type' => 'Mindy\\Router\\Exception\\BadRouteException'
            'errorCode' => 0
            'message' => 'Expecting route variable \'id\''
            'file' => '/home/anton/web/app/vendor/mindy/router/src/Mindy/Router/RouteCollector.php'
            'line' => 65
```

**Comment by max107** [comment]
@mirkoles возможно помогут рекомендации из https://github.com/studio107/Admin/issues/11#issuecomment-128658366

**Comment by max107** [comment]
Исправлено в https://github.com/studio107/User/commit/b57b1cca09a69c21a5a19975f63970a9d83f6e10

Был использован в админке пользователей старый шаблон
