### ISSUE TITLE
не работает поиск после обновления в админ панели 

### ISSUE THREAD

**Issue by mirkoles** [studio107/Admin#11]
После обновления не работает поиск ни "живой" ни по кнопке "лупа".
Не подает признаков жизни, при нажатии на лупу обновляет страницу с 500 ошибкой
![2015-08-07 10 36 48](https://cloud.githubusercontent.com/assets/11004646/9131009/4d12e4a2-3cf0-11e5-8f75-33d1a2129857.png)

**Comment by max107** [comment]
@mirkoles первичные причины могут быть: 

1) Не очищен кеш. Так как шаблонизатор кеширует свои шаблоны, они могут быть старые. Их нужно удалить из папки `app/runtime/cache_templates`. 

2) Не обновлены какие то из модулей: `Admin`, `Core`, `User`. 

Так же в обновлении принимали участие компоненты: `template`, 'router', 'helper', 'orm', 'form'.

Если все выше перечисленное удалено / обновлено, то пожалуйста выставьте `$debug = true` и дайте выбрасываемое исключение, чтобы понять суть ошибки.

**Comment by max107** [comment]
Для добавления "live" поиска обновите `static_admin`

**Comment by mirkoles** [comment]
Кеш очищен, обновлено все, static_admin еще раз, $debug выставлен.
Ситуация не изменилась, исключений не наблюдаю.
```php
 defined('MINDY_PATH') or define('MINDY_PATH', 
dirname(__FILE__) . DIRECTORY_SEPARATOR);

define ('SXGEO_FILE', 0);
define ('SXGEO_MEMORY', 1);
define ('SXGEO_BATCH',  2);

$debug = true;
if ($debug) {
    defined('YII_DEBUG') or define('YII_DEBUG', true);
    defined('YII_TRACE_LEVEL') or define('YII_TRACE_LEVEL', 3);
    defined('YII_ENABLE_ERROR_HANDLER') or define('YII_ENABLE_ERROR_HANDLER', true);
    defined('YII_ENABLE_EXCEPTION_HANDLER') or define('YII_ENABLE_EXCEPTION_HANDLER', true);
    ini_set('error_reporting', 0);
    error_reporting(-1);
}

$config = MINDY_PATH . '../app/config/settings';
if (is_file($config . '_local.php')) {
    $config .= '_local';
}
if (!is_file(MINDY_PATH . '../app/vendor/autoload.php')) {
    throw new Exception("Please run 'composer install' in app/ directory");
}
$autoload = include(MINDY_PATH . '../app/vendor/autoload.php');
$autoload->add('Modules\\', MINDY_PATH . '../app');
$app = \Mindy\Base\Mindy::getInstance($config . '.php');
$app->run();
```

**Comment by max107** [comment]
В приведенном коде `index.php` используется старые константы одной из ранних версий `Mindy`, времен, когда `Application` и `ErrorHandler` был не до конца портирован из Yii. 

Актуальный `index.php` выглядит так:

```php
defined('MINDY_PATH') or define('MINDY_PATH', dirname(__FILE__) . DIRECTORY_SEPARATOR);

$debug = true;
if ($debug) {
    defined('MINDY_DEBUG') or define('MINDY_DEBUG', true);
    defined('MINDY_TRACE_LEVEL') or define('MINDY_TRACE_LEVEL', 3);
    defined('MINDY_ENABLE_ERROR_HANDLER') or define('MINDY_ENABLE_ERROR_HANDLER', true);
    defined('MINDY_ENABLE_EXCEPTION_HANDLER') or define('MINDY_ENABLE_EXCEPTION_HANDLER', true);
    ini_set('error_reporting', -1);
}
$config = MINDY_PATH . '../app/config/settings';
if (is_file($config . '_local.php')) {
    $config .= '_local';
}

// Composer autoloader
if (!is_file(MINDY_PATH . '../app/vendor/autoload.php')) {
    throw new Exception("Please run 'composer install' in app/ directory");
}

include(MINDY_PATH . '../app/vendor/autoload.php');

$app = \Mindy\Base\Mindy::getInstance($config . '.php');
$app->run();
```

`AuraLoader` уже не используется. Для этого используется `composer` в `app/composer.json`:

```json
...
    "autoload": {
        "psr-4": {
            "Modules\\": "Modules"
        }
    },
...
```

Далее попробуйте выставить `error_reporting` в `-1` ИЛИ `display_errors` в `off`.

Если произошла ошибка, исключение должно выбрасываться при любом стечении обстоятельств в коде. На крайний случай мы должны увидеть в логах php сервера или в логах apache | fpm фатальную ошибку.

**Comment by max107** [comment]
@mirkoles шаблоны админки не перекрыты глобально или на уровне `ModelTyreAdmin`?

**Comment by mirkoles** [comment]
Спасибо за ожидание. Нет шаблоны админки не перекрыты. ```index.php``` поправили, ```composer.json``` тоже. 
По итогу логи apache
```log
PHP Fatal error:  Class 'Mindy\Orm\Q\OrQ' not found in /home/anton/web/app/Modules/Admin/Components/ModelAdmin.php on line 608
```

**Comment by mirkoles** [comment]
PS.
Тоже было сделано
```bash
➜  app git:(master) ✗ php composer.phar dump-autoload --optimize --no-dev 
Generating optimized autoload files
```

**Comment by max107** [comment]
Насколько я могу судить по логам в классе `ModelAdmin` используется `use Mindy\Orm\Q\OrQ;` следовательно классы `Q`, `OrQ` отсутствуют в `Mindy\Orm` раз автолоадер не может их найти. Следовательно нужно обновить ORM.

**Comment by mirkoles** [comment]
Все обновлено, все работает, спасибо.

**Comment by max107** [comment]
:+1:
